function T = FK(Joint_Angles)
% Joint_Angles: Array of joint angles in radian

% Link Length in meter
Link_Length = ([180,180,210,210,200,200,126])/1000;

% Transformation Matrix
T = Tz(Link_Length(1))*...
    Rz(Joint_Angles(1))*Tz(Link_Length(2))*....
    Ry(Joint_Angles(2))*Tz(Link_Length(3))*....
    Rz(Joint_Angles(3))*Tz(Link_Length(4))*....
    Ry(Joint_Angles(4))*Tz(Link_Length(5))*...
    Rz(Joint_Angles(5))*Tz(Link_Length(6))*...
    Ry(Joint_Angles(6))*Tz(Link_Length(7))*...
    Rz(Joint_Angles(7));

end