function J = jacobian_(Joint_Angles)
% Joint_Angles: Array of joint angles in radian

% Link Length in meter
Link_Lengths = ([180,180,210,210,200,200,126])/1000;

T = FK(Joint_Angles);
T(1:3,4) = 0;
T = T';

%% J1 
Td = Tz(Link_Lengths(1))*...
     dRz(Joint_Angles(1))*Tz(Link_Lengths(2))*....
     Ry(Joint_Angles(2))*Tz(Link_Lengths(3))*....
     Rz(Joint_Angles(3))*Tz(Link_Lengths(4))*....
     Ry(Joint_Angles(4))*Tz(Link_Lengths(5))*...
     Rz(Joint_Angles(5))*Tz(Link_Lengths(6))*...
     Ry(Joint_Angles(6))*Tz(Link_Lengths(7))*...
     Rz(Joint_Angles(7))*T;

J1 = [Td(1,4), Td(2,4), Td(3,4), Td(3,2), Td(1,3), Td(2,1)]'; 

%% J2
Td = Tz(Link_Lengths(1))*...
     Rz(Joint_Angles(1))*Tz(Link_Lengths(2))*....
     dRy(Joint_Angles(2))*Tz(Link_Lengths(3))*....
     Rz(Joint_Angles(3))*Tz(Link_Lengths(4))*....
     Ry(Joint_Angles(4))*Tz(Link_Lengths(5))*...
     Rz(Joint_Angles(5))*Tz(Link_Lengths(6))*...
     Ry(Joint_Angles(6))*Tz(Link_Lengths(7))*...
     Rz(Joint_Angles(7))*T;

J2 = [Td(1,4), Td(2,4), Td(3,4), Td(3,2), Td(1,3), Td(2,1)]' ;

%% J3
Td = Tz(Link_Lengths(1))*...
     Rz(Joint_Angles(1))*Tz(Link_Lengths(2))*....
     Ry(Joint_Angles(2))*Tz(Link_Lengths(3))*....
     dRz(Joint_Angles(3))*Tz(Link_Lengths(4))*....
     Ry(Joint_Angles(4))*Tz(Link_Lengths(5))*...
     Rz(Joint_Angles(5))*Tz(Link_Lengths(6))*...
     Ry(Joint_Angles(6))*Tz(Link_Lengths(7))*...
     Rz(Joint_Angles(7))*T;

J3 = [Td(1,4), Td(2,4), Td(3,4), Td(3,2), Td(1,3), Td(2,1)]' ;

%% J4
Td = Tz(Link_Lengths(1))*...
     Rz(Joint_Angles(1))*Tz(Link_Lengths(2))*....
     Ry(Joint_Angles(2))*Tz(Link_Lengths(3))*....
     Rz(Joint_Angles(3))*Tz(Link_Lengths(4))*....
     dRy(Joint_Angles(4))*Tz(Link_Lengths(5))*...
     Rz(Joint_Angles(5))*Tz(Link_Lengths(6))*...
     Ry(Joint_Angles(6))*Tz(Link_Lengths(7))*...
     Rz(Joint_Angles(7))*T;

J4 = [Td(1,4), Td(2,4), Td(3,4), Td(3,2), Td(1,3), Td(2,1)]' ;

%% J5
Td = Tz(Link_Lengths(1))*...
     Rz(Joint_Angles(1))*Tz(Link_Lengths(2))*....
     Ry(Joint_Angles(2))*Tz(Link_Lengths(3))*....
     Rz(Joint_Angles(3))*Tz(Link_Lengths(4))*....
     Ry(Joint_Angles(4))*Tz(Link_Lengths(5))*...
     dRz(Joint_Angles(5))*Tz(Link_Lengths(6))*...
     Ry(Joint_Angles(6))*Tz(Link_Lengths(7))*...
     Rz(Joint_Angles(7))*T;

J5 = [Td(1,4), Td(2,4), Td(3,4), Td(3,2), Td(1,3), Td(2,1)]' ;

%% J6
Td = Tz(Link_Lengths(1))*...
     Rz(Joint_Angles(1))*Tz(Link_Lengths(2))*....
     Ry(Joint_Angles(2))*Tz(Link_Lengths(3))*....
     Rz(Joint_Angles(3))*Tz(Link_Lengths(4))*....
     Ry(Joint_Angles(4))*Tz(Link_Lengths(5))*...
     Rz(Joint_Angles(5))*Tz(Link_Lengths(6))*...
     dRy(Joint_Angles(6))*Tz(Link_Lengths(7))*...
     Rz(Joint_Angles(7))*T;

J6 = [Td(1,4), Td(2,4), Td(3,4), Td(3,2), Td(1,3), Td(2,1)]' ;

%% J7
Td = Tz(Link_Lengths(1))*...
     Rz(Joint_Angles(1))*Tz(Link_Lengths(2))*....
     Ry(Joint_Angles(2))*Tz(Link_Lengths(3))*....
     Rz(Joint_Angles(3))*Tz(Link_Lengths(4))*....
     Ry(Joint_Angles(4))*Tz(Link_Lengths(5))*...
     Rz(Joint_Angles(5))*Tz(Link_Lengths(6))*...
     Ry(Joint_Angles(6))*Tz(Link_Lengths(7))*...
     dRz(Joint_Angles(7))*T;

J7 = [Td(1,4), Td(2,4), Td(3,4), Td(3,2), Td(1,3), Td(2,1)]' ;

%% Jacobian
J = ([J1,J2,J3,J4,J5,J6,J7]);
end